### ISSUE TITLE
Inherit Not Working When Specifying a Specific JSON

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#81] opened 2017-01-21 04:16 UTC
When I try to spawn a dungeon that inherit's loot by using /roguelike dungeon here _dungeon name_, it does not inherit the contents of the .json files it is supposed to inherit from. Spawning the dungeon with /roguelike dungeon here does work.

**Comment by EnderStar** [comment] 2017-01-22 05:42
Are the inherited files first alphabetically?

**Comment by Alan19** [comment] 2017-01-22 15:54
Yes. It's no that big of a deal since I have all of the custom dungeons spawning in specific biomes and I can use nature's compass to teleport to those biomes and spawn them there.

**Comment by Greymerk** [comment] 2017-01-22 20:13
It used to be that they were processed in alphabetical order. The reason for this was that they were assembled on first load. Now what happens is that each setting is built separately on load, and then assembled on the fly, meaning that all the inheritance is performed right before each dungeon is being constructed. Meaning order no longer matters, all that matters is your inheritance list.

Each rule you specify in your loot rules is handled independently, if the order seems to matter then that's unintended behavior.

Also, the inheritance refers to the name field inside your setting files, just not the file name.

"name" : "mysetting"

**Comment by Greymerk** [comment] 2017-01-22 21:05
Actually this is looking like a bug in the way inherits work with command spawning. Will probably need to fix it.

**Comment by Greymerk** [comment] 2017-01-28 23:50
I believe this particular issue was addressed in the latest release.

**Closed by Greymerk** 2017-01-28 23:50 UTC
Labels: bug
