### ISSUE TITLE
 at greymerk.roguelike.dungeon.Dungeon.validLocation

### ISSUE THREAD

**Issue by whatthedrunk** [Greymerk/minecraft-roguelike#72] opened 2016-12-01 04:43 UTC
http://pastebin.com/HrswBGWK

Get this when exploring new chunks, once I log back in its fine.

**Comment by Greymerk** [comment] 2016-12-04 19:29
Duplicate of #73 
Fixed in latest release.

**Closed by Greymerk** 2016-12-04 19:29 UTC
