### ISSUE TITLE
Server lockup with v1.3.5

### ISSUE THREAD

**Issue by Dav92** [Greymerk/minecraft-roguelike#11] opened 2014-11-15 13:52 UTC
The following happens on SSP and SMP (with both only forge and cauldron) with forge 1231 and roguelike v1.3.5. It doesn't matter wether I have only roguelike or another ~50mods installed.

While generating the map, the server locks up (please look at the screenshot for info on the method). 
http://abload.de/image.php?img=profilerr9uh1.png

It happens on a map with the seed -878678536829659803
You can reproduce it by teleporting to the coordinates -923/-6022 (x/z) and then go towards -927/-5492 (http://abload.de/image.php?img=coordslockup99ueo.png). It doesn't happen, if you teleport yourself straight to -927/-5492

**Comment by BionicFelps** [comment] 2015-02-05 19:31
I can confirm this issue in my modpack.  (not trying to advertise, but you need specific settings to make the same world, and this is the easiest way to give them to you... The feed the beast pack code is: Minimatech
the pack has the same name as the code)

Create a Biomes O' Plenty world with the seed 6597839188171159067
and the lockup happens around -2172, 1923

I downloaded the most updated source code and compiled it, did not have the issue with it, and indeed there was a Roguelike dungeon right near there.  I don't know if the issue is fixed in the latest code, or if the dungeon is just generating slightly differently, causing the issue to not pop up at that particular dungeon.

**Comment by Greymerk** [comment] 2015-02-13 00:24
I think it's possible that my current method for generating the skeleton of the dungeon can, in extremely rare cases, cause an infinite loop.

This is really old code and my plan is to completely rewrite/replace this part of the codebase for the next release.

Probably won't be much longer until I get to that point.

**Comment by Terpo** [comment] 2015-05-17 10:08
Did you fixed this lockup in the newer version (1.3.5+)? We are still playing on that version and got our first lockup this morning and our world is quite large. I see that you did some changes in this file 3 months ago, but did you fix this one? :)

**Comment by Greymerk** [comment] 2016-01-18 19:44
This code has been rewritten, going to assume it's fixed for now unless there are new reports on this issue.

**Closed by Greymerk** 2016-01-18 19:44 UTC
