### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by MJRamon** [Greymerk/minecraft-roguelike#53] opened 2016-05-18 00:28 UTC
This happens not every time, but happens.
Gen Type: Realistic Terrain Generation 1.9-2.0.0-alpha.3

http://pastebin.com/3hHEAGyT

**Comment by MJRamon** [comment] 2016-05-18 05:13
Also, if the world was created, it seems that Roguelike has some problems with Realistic Terrain Generator and AbyssalCraft (without Roguelike there were no such errors)

http://pastebin.com/T4ALgZZx

**Comment by MJRamon** [comment] 2016-05-18 05:26
Aaand also, while looking around the world, the game crashes sometimes

http://pastebin.com/QePH6RdZ

**Comment by MrRiegel** [comment] 2016-05-18 14:49
ditto

**Comment by DrasticDemise** [comment] 2016-05-23 16:28
Can confirm this crash using Realistic Terrain Generation and AbyssalCraft

**Comment by Greymerk** [comment] 2016-05-23 22:28
Duplicate of #51

It's a bug related to the alpha version of RTG. They're planning a rewrite in which they hope to fix the issue.

**Closed by Greymerk** 2016-05-23 22:28 UTC
